
{{- $simpleName := include "helperfunc.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $simpleName "config" }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}