apiVersion: v1
kind: Service
metadata:
  name: {{ include "helperfunc.fullname" . }}-app
  labels:
    {{- include "helperfunc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "helperfunc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
