{{- if .Values.app.jobs }}
{{- $simpleName := include "helperfunc.name" . -}}
{{- $labels := include "helperfunc.labels" . -}}
{{- $servAccount := include "helperfunc.serviceAccountName" . -}}
{{- $dbfullname := include "helperfunc.postgresql.fullname" . -}}
{{- range $job := .Values.app.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" $simpleName $job.name }}-app
  labels:
    type: {{ $job.name }}
    {{- $labels | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ printf "%s-%s" $simpleName $job.name }}
        image: "{{ $.Values.image.api_repository }}:{{ $.Values.image.api_tag | default $.Chart.AppVersion }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- with $job.command }}
        command: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if $.Values.configMap }}
        envFrom:
        - configMapRef:
            name: {{ printf "%s-%s" $simpleName "config" }}-dbmigrations
        {{- end }}
      initContainers:
        - name: init-db
          image: busybox:1.34.1
          command: ['sh', '-c', 'while ! nc -v -z $DATABASE_HOST $DATABASE_PORT </dev/null; do sleep 5; done']
          {{- if $.Values.configMap }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s" $simpleName "config" }}-dbmigrations
          {{- end }}
      restartPolicy: Never
{{- end -}}
{{- end -}}