{{- if .Values.app.jobs }}
{{- $simpleName := include "helperfunc.name" . -}}
{{- $labels := include "helperfunc.labels" . -}}
---
{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $simpleName "config" }}-dbmigrations
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_HOST: {{ include "helperfunc.postgresql.fullname" . | quote }}
  DATABASE_PORT: {{ .Values.postgresql.service.port | quote }}
  ARLO_DB__uri: postgresql://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ include "helperfunc.postgresql.fullname" . }}:{{ .Values.postgresql.service.port }}/{{ include "helperfunc.postgresql.database" . }}
  ARLO_DB__connect_args: {{ .Values.database.connect_args | quote }} 
  {{- else }}
  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  ARLO_DB__uri: postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}
  ARLO_DB__connect_args: {{ .Values.database.connect_args | quote }} 
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ include "helperfunc.redis.host" . | quote }}
  REDIS_PORT: {{ include "helperfunc.redis.port" . | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- else }}
  REDIS_HOST: {{ .Values.redisDb.host }}
  REDIS_PORT: {{ .Values.redisDb.port | quote }}
  REDIS_PASSWORD: {{ .Values.redisDb.password | quote }}
  {{- end }}
{{- end }}
{{- end }}