{{- if .Values.configMap.enabled }}
{{- $simpleName := include "helperfunc.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $simpleName "config" }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ if kindIs "slice" $v }}{{ $v | toJson | quote }}{{ else }}{{ $v | quote }}{{ end }}
  {{- end }}
{{- end }}