{{- if .Values.configMap.enabled }}
{{- $simpleName := include "helperfunc.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $simpleName "config" }}
data:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  DATABASE_HOST: {{ include "helperfunc.postgresql.fullname" . | quote }}
  DATABASE_PORT: {{ .Values.postgresql.service.port | quote }}
  DATABASE_NAME: {{ include "helperfunc.postgresql.database" . | quote }}
  DATABASE_USER: {{ .Values.postgresql.postgresqlUsername }}
  DATABASE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | quote }}
  {{- else }}
  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  ARLO_DB__uri: {{ .Values.database.uri | quote }}
  ARLO_DB__connect_args: {{ .Values.database.connect_args | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ include "helperfunc.redis.host" . | quote }}
  REDIS_PORT: {{ include "helperfunc.redis.port" . | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  {{- else }}
  REDIS_HOST: {{ .Values.redisDb.host }}
  REDIS_PORT: {{ .Values.redisDb.port | quote }}
  REDIS_PASSWORD: {{ .Values.redisDb.password | quote }}
  {{- end }}
{{- end }}