# Ref: htpasswd -nb admin A393MsaX | openssl base64
{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: flower-auth
data:
  users: YWRtaW46JGFwcjEkLlBhWWo0NFIkaGwvZC5aZnkzb1AuNlhvZjVuU2QwLgoK
{{- end }}