{{- if .Values.flower.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helperfunc.fullname" . }}-flower
  labels:
    {{- include "helperfunc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    {{- include "helperfunc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flower
  {{- end -}}
