{{- if .Values.cnab.enabled -}}
{{- $simpleName := include "helperfunc.name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helperfunc.fullname" . }}-cnab
  labels:
    app.kubernetes.io/component: cnab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: cnab
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: cnab
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helperfunc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.cnab_repository }}:{{ .Values.image.cnab_tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.cnab.command }}
          command: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $.Values.configMap }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s" $simpleName "config" }}
          {{- end }}
          volumeMounts:
            - name: rclone-config
              mountPath: "/root/.config/rclone/rclone.conf"
              subPath: rclone.conf
              readOnly: true
            - name: rclone-cnab-cron
              mountPath: "/etc/cron.d/rclone_cnab_cron"
              subPath: rclone_cnab_cron
              readOnly: true
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        - name: rclone-config
          secret:
            secretName: rclone-config
            items:
              - key: rclone.conf
                path: rclone.conf
              - key: rclone_cnab_cron
                path: rclone_cnab_cron
      {{- with .Values.cnab.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cnab.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cnab.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}