{{- if .Values.cnab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
type: "Opaque"
stringData:
  rclone.conf: |
    [s3-remoto]
    type = s3
    provider = {{ .Values.cnab.s3_provider }}
    access_key_id = {{ .Values.env.ARLO_S3__ACCESS_KEY_ID }}
    secret_access_key = {{ .Values.env.ARLO_S3__SECRET_ACCESS_KEY }}
    region = {{ .Values.env.ARLO_S3__REGION_NAME }}
{{- end }}