{{- if .Values.cnab.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-config
type: "Opaque"
stringData:
  rclone.conf: |
    [s3-remoto]
    type = s3
    provider = {{ .Values.cnab.s3_provider }}
    access_key_id = {{ .Values.env.ARLO_S3__ACCESS_KEY_ID }}
    secret_access_key = {{ .Values.env.ARLO_S3__SECRET_ACCESS_KEY }}
    region = {{ .Values.env.ARLO_S3__REGION_NAME }}
  rclone_cnab_cron: |
    * * * * * root rclone copy {{ .Values.env.ARLO_REMESSA_CNAB__RETORNO_FOLDER_PATH}} s3-remoto:{{ .Values.env.ARLO_S3__CNAB_BUCKET }}/{{ .Values.env.ARLO_REMESSA_CNAB__RETORNO_S3_FOLDER }}  >> /var/log/cron.log 2>&1
    * * * * * root rclone copy {{ .Values.env.ARLO_REMESSA_CNAB__PROCESSADO_FOLDER_PATH}} s3-remoto:{{ .Values.env.ARLO_S3__CNAB_BUCKET }}/{{ .Values.env.ARLO_REMESSA_CNAB__PROCESSADO_S3_FOLDER }}  >> /var/log/cron.log 2>&1
    * * * * * root rclone copy {{ .Values.env.ARLO_REMESSA_CNAB__SESSION_LOG_FILE_PATH }} s3-remoto:{{ .Values.env.ARLO_S3__CNAB_BUCKET }}/  >> /var/log/cron.log 2>&1
{{- end }}