# Default values for Chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  api_repository: docker
  # Overrides the image tag whose default is the chart appVersion.
  api_tag: ""
  cnab_repository: docker
  # Overrides the image tag whose default is the chart appVersion.
  cnab_tag: ""
  pullPolicy: Always
imagePullSecrets:
  - name: ecr-registry-secret

nameOverride: ""
fullnameOverride: ""

env: {}

dbless: false

database:
  host: localhost
  port: 5432
  name: default
  user: postgres
  password: postgres
  connect_args: "{}"

redisDb:
  host: localhost
  port: 6379
  password: ""

configMap:
  enabled: true

certificados:
  enabled: false
  secretName: "arlo-certs"
  volumeMountPath: "/code/arlo/financeiro/certs"
  acName: "ac.pem"
  certificadoName: "certificado.pem"
  chavePrivadaName: "certificado.key"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

app:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  command: []
    # - uvicorn 
    # - fastapi.api:app 
    # - --host 
    # - 0.0.0.0 
    # - --port 
    # - 8000 
    # - --reload
  jobs: []
    # - name: migrate
    #   command:
    #     - "alembic"
    #     - "upgrade"
    #     - "head"
  ingressroute:
    enabled: true
    entrypoints:
      - web
      - websecure
    hosts: []
      # - api.arlo.com.br
    hostStr: ""
    redirectHttps: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
  healthcheck:
    enabled: true
    path: /healthz/
    port: 8000
    livenessprobe:
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
    readinessprobe:
      initialDelaySeconds: 5
      periodSeconds: 20
      timeoutSeconds: 10
      failureThreshold: 3
  service:
    type: ClusterIP
    port: 80
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
cnab:
  enabled: true
  command: []
  skyunix:
    enabled: false
    storage:
      enabled: false
      storageSize: 2Gi
      storageClassName: nfs
      volumeName: nfs-data
  s3_provider: AWS
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
worker:
  enabled: false
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 90
    targetMemoryUtilizationPercentage: 80
  command: []
    # - celery
    # - -A
    # - arlo.celery_app.app
    # - worker
    # - -l
    # - info
  liveness:
    command: []
  resources:
    limits:
      cpu: 900m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: { }
  tolerations: [ ]
  affinity: { }

beat:
  enabled: false
  command: []
    # - celery
    # - -A
    # - arlo.celery_app.app
    # - beat
    # - -S
    # - redbeat.RedBeatScheduler
    # - --max-interval
    # - 30
    # - -l
    # - info

flower:
  enabled: false
  prefix: "/flower"
  command: []
    # - celery
    # - -A
    # - arlo.celery_app.app
    # - flower
    # - broker_api=amqp://usuario:password@host:porta/vhost
    # - -l
    # - info
  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 64Mi

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 64Mi

redis:
  enabled: false
  nameOverride: redis
  auth:
    password: CspeR7s16d
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 1
    persistence:
      enabled: false

# Default to disabled, use a managed database service. But can be enabled here.
postgresql:
  enabled: false
  nameOverride: postgresql
  postgresqlPassword: G65df98
